### PR TITLE
Escape user provided comment

### PR DESCRIPTION
**Pull request by morenoh149**
fixes https://github.com/keystonejs/keystone/issues/2103#issuecomment-197056426

### CODE REVIEW

**Comment by morenoh149** [comment]
@mxstbr lmk if it works

**Comment by mxstbr** [comment]
Don't actually have permission to merge anything here I'm afraid... Looks good to me from the code, I'll kick Jed to add me to the appropriate group!

**Comment by mxstbr** [comment]
Can verify this works and is ready to merge! 

screen shot 2016-03-16 at 15 06 23

**Comment by JedWatson** [comment]
Done! Perms fixed too @mxstbr. Thanks @morenoh149!

**Pull request merged**
